### ISSUE TITLE
KITTI Benchmark

### ISSUE THREAD

**Issue by qiaozhijian** [Pamphlett/Segregator#1]
Hello, thanks for your great work!

How can I reproduce the KITTI benchmark to follow your work?

Could you provide preprocessed dataset of KITTI?

**Comment by Pamphlett** [comment]
Hi @qiaozhijian,

Thanks for your interest in the work. I uploaded evaluation protocols in the [material folder](https://github.com/Pamphlett/Segregator/tree/main/materials), where each line stands for the index of the corresponding scans to be registered.

Basically, the protocols are generated by Eq. 10 in the paper and looping through every scan in each chosen sequence. Repetitive ones are eliminated of course.

Hope it helps!

**Comment by qiaozhijian** [comment]
Hi @Pamphlett Thanks!
