### ISSUE TITLE
The efficient way to get the estimated `.label` file

### ISSUE THREAD

**Issue by LimHyungTae** [Pamphlett/Segregator#2]
Hello, I'm the author of Quatro and I really like your paper! Haha

I'm writing this issue to ask you how to get `.label` file efficiently.

I followed your instruction, and noticed Salsanext already has saving pipeline; unfortunately, Salsanext does not guarantee the number of labels, so mostly # of labels != # points.

Could you please provide me with your label files? Thank you in advance!

**Comment by Pamphlett** [comment]
Hi HyungTae!

Thanks for reaching out!
Of course I know you haha :) I noticed your work a long time ago and Quatro is really nice work!
For the semantic label generation, I did not use Salsanext but SPVNAS (on KITTI), where I did not encounter the number inconsistency issue. If you need any help regarding SPVNAS, do not hesitate to discuss it here!

**Comment by LimHyungTae** [comment]
Thx for prompt reply and it works!

Here's my code snippet in `evaluate.py` in [SPVNAS repository](https://github.com/mit-han-lab/spvnas) for other researchers:
```
abs_input_path = feed_dict['file_name'][0].split("/")
output_file_name = args.save_dir + "/" + abs_input_path[-3] + "/" + abs_input_path[-1].replace('.bin', '.label')
sem = outputs.cpu().numpy().astype(np.uint32)
ins = np.zeros_like(sem).astype(np.uint32)
pred_eval = sem + (ins << 16)
pred_eval.astype(np.uint32).tofile(output_file_name)
```

* I added `args.save_dir` parameter
* `abs_input_path[-3]`: sequence number, e.g., 00, 01, ...
* `abs_input_path[-1]`: frame number, e.g., 000000, 000001, ..., 004000, ...

**Comment by LimHyungTae** [comment]
Like this:
![image](https://github.com/Pamphlett/Segregator/assets/35317311/73b6fefa-dde0-4e18-8b0b-dc53b54d6e50)

**Comment by LimHyungTae** [comment]
This issue ganna be closed; yet, it would be better if you provide one with pre-extracted labels in the future :)

**Comment by Pamphlett** [comment]
Hi HyungTae!

Thanks for your advice. And I put this issue on the top to let more people know :)
